services:
  auth:
    build:
      context: .                 # ← racine du repo
      dockerfile: auth-service/Dockerfile
    ports: ["8090:8090"]

  cinema:
    build:
      context: .
      dockerfile: cinema-service/Dockerfile
    ports: ["8091:8091"]

  movie:
    build:
      context: .
      dockerfile: movie-service/Dockerfile
    ports: ["8092:8092"]

  schedule:
    build:
      context: .
      dockerfile: schedule-service/Dockerfile
    ports: ["8093:8093"]

  public:
    build:
      context: .
      dockerfile: public-service/Dockerfile
    ports: ["8094:8094"]

  gateway:
    build:
      context: .
      dockerfile: api-gateway/Dockerfile
    ports: ["8095:8095"]
